# Generated by Django 5.0.2 on 2024-03-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPRSS', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
