# Generated by Django 5.0.2 on 2024-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRSS', '0005_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageDirectoryEntrySecurity', models.CharField(max_length=50)),
                ('CheckSum', models.CharField(max_length=50)),
                ('SizeOfInitializedData', models.CharField(max_length=50)),
                ('SizeOfImage', models.CharField(max_length=50)),
                ('MajorLinkerVersion', models.CharField(max_length=50)),
                ('AddressOfEntryPoint', models.CharField(max_length=50)),
                ('SectionMinEntropy', models.CharField(max_length=50)),
                ('DirectoryEntryImportSize', models.CharField(max_length=50)),
                ('SectionMaxPhysical', models.CharField(max_length=50)),
                ('SectionMinVirtualSize', models.CharField(max_length=50)),
                ('SectionMaxPointerData', models.CharField(max_length=50)),
                ('e_lfanew', models.CharField(max_length=50)),
                ('DllCharacteristics', models.CharField(max_length=50)),
                ('DirectoryEntryImport', models.CharField(max_length=50)),
                ('ImageDirectoryEntryResource', models.CharField(max_length=50)),
                ('ImageDirectoryEntryImport', models.CharField(max_length=50)),
                ('DirectoryEntryExport', models.CharField(max_length=50)),
                ('SizeOfCode', models.CharField(max_length=50)),
                ('ImageBase', models.CharField(max_length=50)),
                ('SizeOfStackReserve', models.CharField(max_length=50)),
            ],
        ),
    ]
