# Generated by Django 5.0.2 on 2024-03-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRSS', '0007_remove_features_addressofentrypoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='features_vector',
        ),
        migrations.AddField(
            model_name='features',
            name='AddressOfEntryPoint',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='CheckSum',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='DirectoryEntryExport',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='DirectoryEntryImport',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='DirectoryEntryImportSize',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='DllCharacteristics',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='ImageBase',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='ImageDirectoryEntryImport',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='ImageDirectoryEntryResource',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='ImageDirectoryEntrySecurity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='MajorLinkerVersion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='SectionMaxPhysical',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='SectionMaxPointerData',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='SectionMinEntropy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='SectionMinVirtualSize',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='SizeOfCode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='SizeOfImage',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='SizeOfInitializedData',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='SizeOfStackReserve',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='e_lfanew',
            field=models.CharField(default='', max_length=50),
        ),
    ]
