# Generated by Django 5.0.2 on 2024-03-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRSS', '0008_remove_features_features_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='AddressOfEntryPoint',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='CheckSum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='DirectoryEntryExport',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='DirectoryEntryImport',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='DirectoryEntryImportSize',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='DllCharacteristics',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='ImageBase',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='ImageDirectoryEntryImport',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='ImageDirectoryEntryResource',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='ImageDirectoryEntrySecurity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='MajorLinkerVersion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='SectionMaxPhysical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='SectionMaxPointerData',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='SectionMinEntropy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='SectionMinVirtualSize',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='SizeOfCode',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='SizeOfImage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='SizeOfInitializedData',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='SizeOfStackReserve',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='features',
            name='e_lfanew',
            field=models.FloatField(default=0.0),
        ),
    ]
