# Generated by Django 5.0.2 on 2024-03-09 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRSS', '0010_fileupload_alter_register_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
