# Generated by Django 5.0.2 on 2024-03-29 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPRSS', '0011_features_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='doc_file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='PPRSS/wmpnssui.dll.mui', upload_to='static/pefiles/'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
